# Generated by Django 3.0.5 on 2020-06-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
