# Generated by Django 3.0.5 on 2020-06-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200618_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
